use std::io::Error;

pub async fn phase4() -> Result<Vec<()>, Error> {
    todo!()
}